### ISSUE TITLE
[errors when loading] ModuleNotFoundError: No module named 'plugins.processing.algs.qgis.DeleteDuplicateGeometries' 

### ISSUE THREAD

**Issue by CWen001** [achic19/poi_visibility_network#2]
Hello. I'm trying to load the plugin after successfully installed it. However, in my Qgis 3.16.7 or 3.18.1 on windows 10, it always shows the ModuleNotFoundError:

ModuleNotFoundError: No module named 'plugins.processing.algs.qgis.DeleteDuplicateGeometries' 

The picture was attached. I have tried different versions of Qgis but the error is the same. May I ask if I miss something? Thank you very much.

```
Couldn't load plugin 'poi_visibility_network' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'plugins.processing.algs.qgis.DeleteDuplicateGeometries' 
Traceback (most recent call last):
  File "D:/ProgramData/Anaconda3/envs/qgis_conda/Library/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\poi_visibility_network\__init__.py", line 35, in classFactory
    from .poi_visibility_network import PoiVisibilityNetwork
  File "D:/ProgramData/Anaconda3/envs/qgis_conda/Library/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\poi_visibility_network\poi_visibility_network.py", line 40, in 
    from .work_folder.mean_close_point.mean_close_point import *
  File "D:/ProgramData/Anaconda3/envs/qgis_conda/Library/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\poi_visibility_network\work_folder\mean_close_point\mean_close_point.py", line 15, in 
    from plugins.processing.algs.qgis.DeleteDuplicateGeometries import *
  File "D:/ProgramData/Anaconda3/envs/qgis_conda/Library/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'plugins.processing.algs.qgis.DeleteDuplicateGeometries'


Python version: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:10:34) [MSC v.1916 64 bit (AMD64)] 
QGIS version: 3.16.7-Hannover Hannover, exported 

Python Path:
C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sdna
D:/Program Files (x86)/sDNA
C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geohey_toolbox
D:/ProgramData/Anaconda3/envs/qgis_conda/Library/./python
C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/ProgramData/Anaconda3/envs/qgis_conda/Library/./python/plugins
D:\ProgramData\Anaconda3\envs\qgis_conda\Library\python
D:\ProgramData\Anaconda3\envs\qgis_conda\Library\python\plugins
D:\chen
D:\ProgramData\Anaconda3\envs\qgis_conda\python39.zip
D:\ProgramData\Anaconda3\envs\qgis_conda\DLLs
D:\ProgramData\Anaconda3\envs\qgis_conda\lib
D:\ProgramData\Anaconda3\envs\qgis_conda\Library\bin
D:\ProgramData\Anaconda3\envs\qgis_conda
D:\ProgramData\Anaconda3\envs\qgis_conda\lib\site-packages
D:\ProgramData\Anaconda3\envs\qgis_conda\lib\site-packages\win32
D:\ProgramData\Anaconda3\envs\qgis_conda\lib\site-packages\win32\lib
D:\ProgramData\Anaconda3\envs\qgis_conda\lib\site-packages\Pythonwin
C:/Users/wench/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Program Files\QGIS 3.0\apps\qgis\python\plugins
C:\Program Files\QGIS 3.4\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.0\apps\qgis\python\plugins
C:\Program Files\QGIS 3.4\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.0\apps\qgis\python\plugins
C:\Program Files\QGIS 3.4\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.0\apps\qgis\python\plugins
C:\Program Files\QGIS 3.4\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.0\apps\qgis\python\plugins
C:\Program Files\QGIS 3.4\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.0\apps\qgis\python\plugins
C:\Program Files\QGIS 3.4\apps\qgis-ltr\python\plugins
C:\Program Files\QGIS 3.10\apps\qgis-ltr\python\plugins
```

**Comment by achic19** [comment]
Hi 
Currently , the Plugin has been tested on  3.0 ,3.4 and 3.10 versions. I will test and update the plugin on 3.16 (the latest stable version) and let you know when it is compatible with that version.

**Comment by achic19** [comment]
This plugin has been updated to support Qgis 3.16

**Comment by CWen001** [comment]
Thank you very much for the excellent work! I'm using it in Qgis 3.18 successfully and the plugin looks cool. 

![poi_viz](https://user-images.githubusercontent.com/30044400/121848894-4298fc00-cd1d-11eb-802b-2394d47b43f5.png)
